version: "3.2"

services:
  elasticsearch:
    image: bitnami/elasticsearch:latest
    environment:
      ELASTICSEARCH_PORT_NUMBER: 9200
      discovery.type: "single-node"
      bootstrap.memory_lock: "true"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - app-tier
    volumes:
      - ./data/elastic:/usr/share/elasticsearch/data
  movies-app:
    restart: always
    image: tobiaszimmer/assignment-lsola1-movies:main
    environment:
      MOVIES_ELASTIC_SEARCH_HOST: elasticsearch
      MOVIES_ELASTIC_SEARCH_PORT: 9200
      MOVIES_SERVER_PORT: 8080
    depends_on:
      - elasticsearch
    ports:
      - "8080:8080"
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge
